// TEST-NAVIGATION: Auf false setzen, um die Navigationsleiste vor Veröffentlichung auszublenden.
const SHOW_TEST_NAV = true;
const PASS_KEY = 'attenreith_kinder_pass_v10';
const SECRET_STATIONS = [1,3,5,6];
function getPass(){try{return JSON.parse(localStorage.getItem(PASS_KEY)||'{}')}catch(e){return {}}}
function savePass(p){localStorage.setItem(PASS_KEY,JSON.stringify(p));renderPass()}
function renderPass(){const p=getPass();document.querySelectorAll('#passGrid').forEach(g=>{g.innerHTML='';SECRET_STATIONS.forEach((station,idx)=>{const c=document.createElement('div');c.className='pass-cell'+(p[station]!=null?' filled':'');c.innerHTML='<small>'+(idx+1)+'</small><b>'+(p[station]!=null?p[station]:'–')+'</b>';g.appendChild(c)})});const n=SECRET_STATIONS.filter(k=>p[k]!=null).length;document.querySelectorAll('#passStatus').forEach(x=>x.textContent=n?`${n} von 4 Geheimzahlen gesammelt.`:'Noch keine Geheimzahl gesammelt.')}
function setupNumberHunt(station, secret){renderPass();const form=document.getElementById('numberForm'),wrong=document.getElementById('wrong'),success=document.getElementById('success');if(!form)return;form.addEventListener('submit',e=>{e.preventDefault();wrong.classList.add('hidden');success.classList.add('hidden');const input=document.getElementById('foundNumber');const val=(input.value||'').trim();if(!val){wrong.innerHTML='<strong>Trag zuerst die gefundene Zahl ein.</strong>';wrong.classList.remove('hidden');return}if(val===String(secret)){const p=getPass();p[station]=secret;savePass(p);success.classList.remove('hidden');success.scrollIntoView({behavior:'smooth',block:'start'})}else{wrong.innerHTML='<strong>Diese Zahl ist es noch nicht.</strong><br>Schaut noch einmal ganz genau nach! 👀';wrong.classList.remove('hidden')}})}
function setupTask(){renderPass();document.getElementById('taskDone')?.addEventListener('click',()=>{document.getElementById('taskSuccess')?.classList.remove('hidden');document.getElementById('taskSuccess')?.scrollIntoView({behavior:'smooth',block:'start'})})}
function setupKidsFinal(){renderPass();const p=getPass(),ready=SECRET_STATIONS.every(i=>p[i]!=null),locked=document.getElementById('finalLocked'),box=document.getElementById('finalReady');if(ready){locked.classList.add('hidden');box.classList.remove('hidden')}document.getElementById('checkFinal')?.addEventListener('click',()=>{const expected=SECRET_STATIONS.map(i=>String(getPass()[i])).join('');const val=(document.getElementById('finalCode').value||'').trim();document.getElementById('finalWrong').classList.add('hidden');document.getElementById('finalSuccess').classList.add('hidden');(val===expected?document.getElementById('finalSuccess'):document.getElementById('finalWrong')).classList.remove('hidden')})}
document.addEventListener('DOMContentLoaded',()=>{if(!SHOW_TEST_NAV)document.getElementById('devNav')?.remove();renderPass()});